var mongoose = require('mongoose');

var AppointmentSchema = new mongoose.Schema({
    
  time1: {  sunday: {  patientName: String,
                      phone: String,
                      email: String   },
            monday: {  patientName: String,
                      phone: String,
                      email: String   }, 
            tuesday: {  patientName: String,
                      phone: String,
                      email: String   },
            wednesday: {  patientName: String,
                      phone: String,
                      email: String   },
            thursday: {  patientName: String,
                      phone: String,
                      email: String   },
            friday: {  patientName: String,
                      phone: String,
                      email: String   },
            saturday: {  patientName: String,
                      phone: String,
                      email: String   }           
  },
  time2: {  sunday: {  patientName: String,
                      phone: String,
                      email: String   },
            monday: {  patientName: String,
                      phone: String,
                      email: String   }, 
            tuesday: {  patientName: String,
                      phone: String,
                      email: String   },
            wednesday: {  patientName: String,
                      phone: String,
                      email: String   },
            thursday: {  patientName: String,
                      phone: String,
                      email: String   },
            friday: {  patientName: String,
                      phone: String,
                      email: String   },
            saturday: {  patientName: String,
                      phone: String,
                      email: String   }           
  },
  time3: {  sunday: {  patientName: String,
                      phone: String,
                      email: String   },
            monday: {  patientName: String,
                      phone: String,
                      email: String   }, 
            tuesday: {  patientName: String,
                      phone: String,
                      email: String   },
            wednesday: {  patientName: String,
                      phone: String,
                      email: String   },
            thursday: {  patientName: String,
                      phone: String,
                      email: String   },
            friday: {  patientName: String,
                      phone: String,
                      email: String   },
            saturday: {  patientName: String,
                      phone: String,
                      email: String   }           
  },
  time4: {  sunday: {  patientName: String,
                      phone: String,
                      email: String   },
            monday: {  patientName: String,
                      phone: String,
                      email: String   }, 
            tuesday: {  patientName: String,
                      phone: String,
                      email: String   },
            wednesday: {  patientName: String,
                      phone: String,
                      email: String   },
            thursday: {  patientName: String,
                      phone: String,
                      email: String   },
            friday: {  patientName: String,
                      phone: String,
                      email: String   },
            saturday: {  patientName: String,
                      phone: String,
                      email: String   },          
  },
  time5: {  sunday: {  patientName: String,
                      phone: String,
                      email: String   },
            monday: {  patientName: String,
                      phone: String,
                      email: String   } ,
            tuesday: {  patientName: String,
                      phone: String,
                      email: String   },
            wednesday: {  patientName: String,
                      phone: String,
                      email: String   },
            thursday: {  patientName: String,
                      phone: String,
                      email: String   },
            friday: {  patientName: String,
                      phone: String,
                      email: String   },
            saturday: {  patientName: String,
                      phone: String,
                      email: String   }           
  },
  time6: {  sunday: {  patientName: String,
                      phone: String,
                      email: String   },
            monday: {  patientName: String,
                      phone: String,
                      email: String   } ,
            tuesday: {  patientName: String,
                      phone: String,
                      email: String   },
            wednesday: {  patientName: String,
                      phone: String,
                      email: String   },
            thursday: {  patientName: String,
                      phone: String,
                      email: String   },
            friday: {  patientName: String,
                      phone: String,
                      email: String   },
            saturday: {  patientName: String,
                      phone: String,
                      email: String   }           
  },
  time7: {  sunday: {  patientName: String,
                      phone: String,
                      email: String   },
            monday: {  patientName: String,
                      phone: String,
                      email: String   } ,
            tuesday: {  patientName: String,
                      phone: String,
                      email: String   },
            wednesday: {  patientName: String,
                      phone: String,
                      email: String   },
            thursday: {  patientName: String,
                      phone: String,
                      email: String   },
            friday: {  patientName: String,
                      phone: String,
                      email: String   },
            saturday: {  patientName: String,
                      phone: String,
                      email: String   }           
  },
  time8: {  sunday: {  patientName: String,
                      phone: String,
                      email: String   },
            monday: {  patientName: String,
                      phone: String,
                      email: String   } ,
            tuesday: {  patientName: String,
                      phone: String,
                      email: String   },
            wednesday: {  patientName: String,
                      phone: String,
                      email: String   },
            thursday: {  patientName: String,
                      phone: String,
                      email: String   },
            friday: {  patientName: String,
                      phone: String,
                      email: String   },
            saturday: {  patientName: String,
                      phone: String,
                      email: String   }           
  }
});


module.exports = mongoose.model('Appointment', AppointmentSchema);
